#!/usr/bin/env php
<?php

use Mmo\PhpProfiler\Converter\CorrelationIdGenerator\RandomGenerator;
use Mmo\PhpProfiler\FlameGraph\FilePutContentsWriter;
use Mmo\PhpProfiler\TextUI\Command\CreateFlameGraph;

$possibleFiles = [__DIR__.'/../../autoload.php', __DIR__.'/../autoload.php', __DIR__.'/vendor/autoload.php'];
$file = null;
foreach ($possibleFiles as $possibleFile) {
    if (file_exists($possibleFile)) {
        $file = $possibleFile;

        break;
    }
}

if (null === $file) {
    throw new RuntimeException('Unable to locate autoload.php file.');
}

require_once $file;

(new CreateFlameGraph(new FilePutContentsWriter(new RandomGenerator())))->run($argv);
